version: '2.0'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    entrypoint: "bash -c '/docker-entrypoint.sh elasticsearch -Des.network.host=`hostname --ip-address`'"
  cassandra:
    image: cassandra
    ports:
      - "7199:7199"
      - "9160:9160"
      - "7000:7000"
      - "9042:9042"
      - "61621:61621"
    environment:
      CASSANDRA_START_RPC: 'true'
  titan:
    ports:
      - "8182:8182"
      - "8184:8184"
    depends_on:
      - elasticsearch
      - cassandra
    image: keke/titan-gremlin:0.0.1
    environment:
      ELASTICSEARCH_ADDR: elasticsearch
      ELASTICSEARCH_PORT: 9200
      CASSANDRA_ADDR: cassandra
      CASSANDRA_PORT: 9160
      CASSANDRA_BACKEND: cassandrathrift
